name: PubSubHubbub Ping

on:
  push:
    branches: [main]
    
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for deployment
        run: sleep 600
        
      - name: Ping hubs
        run: |
          RSS_FEED_URL="https://farmaci-online-italia.pages.dev/index.xml"
          
          # Google PubSubHubbub
          echo "🔄 Pinging Google PubSubHubbub..."
          STATUS=$(curl -X POST "https://pubsubhubbub.appspot.com/" \
            -d "hub.mode=publish" \
            -d "hub.url=$RSS_FEED_URL" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -s -o /dev/null -w "%{http_code}")
            
          if [[ "$STATUS" =~ ^(200|202|204)$ ]]; then
            echo "✅ Google hub success! Status: $STATUS"
          else
            echo "❌ Google hub error! Status: $STATUS"
          fi
          
          # Superfeedr (без авторизации)
          echo "🔄 Pinging Superfeedr..."
          STATUS=$(curl -X POST "https://pubsubhubbub.superfeedr.com/" \
            -d "hub.mode=publish" \
            -d "hub.url=$RSS_FEED_URL" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -s -o /dev/null -w "%{http_code}")
            
          if [[ "$STATUS" =~ ^(200|202|204)$ ]]; then
            echo "✅ Superfeedr success! Status: $STATUS"
          else
            echo "❌ Superfeedr error! Status: $STATUS"
          fi